# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_auto_add.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.setWindowModality(QtCore.Qt.NonModal)
        Wizard.resize(468, 300)
        Wizard.setWizardStyle(QtWidgets.QWizard.AeroStyle)
        Wizard.setTitleFormat(QtCore.Qt.PlainText)
        Wizard.setSubTitleFormat(QtCore.Qt.PlainText)
        self.intro = QtWidgets.QWizardPage()
        self.intro.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.intro.setTitle("")
        self.intro.setSubTitle("")
        self.intro.setObjectName("intro")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.intro)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.intro)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_gall = QtWidgets.QRadioButton(self.intro)
        self.radioButton_gall.setObjectName("radioButton_gall")
        self.horizontalLayout_4.addWidget(self.radioButton_gall)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.radioButton_tistory = QtWidgets.QRadioButton(self.intro)
        self.radioButton_tistory.setObjectName("radioButton_tistory")
        self.horizontalLayout_4.addWidget(self.radioButton_tistory)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        Wizard.addPage(self.intro)
        self.tistory1 = QtWidgets.QWizardPage()
        self.tistory1.setObjectName("tistory1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tistory1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_6.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.tistory1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tistory1_input = QtWidgets.QLineEdit(self.tistory1)
        self.tistory1_input.setObjectName("tistory1_input")
        self.horizontalLayout_5.addWidget(self.tistory1_input)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        Wizard.addPage(self.tistory1)
        self.gall1 = QtWidgets.QWizardPage()
        self.gall1.setObjectName("gall1")
        self.gridLayout = QtWidgets.QGridLayout(self.gall1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.gall1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gall1_input = QtWidgets.QLineEdit(self.gall1)
        self.gall1_input.setObjectName("gall1_input")
        self.horizontalLayout.addWidget(self.gall1_input)
        self.gall1_search = QtWidgets.QPushButton(self.gall1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gall1_search.sizePolicy().hasHeightForWidth())
        self.gall1_search.setSizePolicy(sizePolicy)
        self.gall1_search.setObjectName("gall1_search")
        self.horizontalLayout.addWidget(self.gall1_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.gall1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gall1_rec = QtWidgets.QCheckBox(self.groupBox)
        self.gall1_rec.setObjectName("gall1_rec")
        self.horizontalLayout_3.addWidget(self.gall1_rec)
        self.gall1_filter = QtWidgets.QCheckBox(self.groupBox)
        self.gall1_filter.setObjectName("gall1_filter")
        self.horizontalLayout_3.addWidget(self.gall1_filter)
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout.setStretch(0, 30)
        self.verticalLayout.setStretch(1, 150)
        self.verticalLayout.setStretch(2, 100)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        Wizard.addPage(self.gall1)
        self.tistory2 = QtWidgets.QWizardPage()
        self.tistory2.setObjectName("tistory2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tistory2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tistory2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tistory2_info = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tistory2_info.sizePolicy().hasHeightForWidth())
        self.tistory2_info.setSizePolicy(sizePolicy)
        self.tistory2_info.setMaximumSize(QtCore.QSize(16777215, 80))
        self.tistory2_info.setObjectName("tistory2_info")
        self.gridLayout_6.addWidget(self.tistory2_info, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.tistory2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.tistory2_input = QtWidgets.QLineEdit(self.tistory2)
        self.tistory2_input.setObjectName("tistory2_input")
        self.horizontalLayout_6.addWidget(self.tistory2_input)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        Wizard.addPage(self.tistory2)
        self.gall2 = QtWidgets.QWizardPage()
        self.gall2.setObjectName("gall2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gall2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.gall2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gall2_info = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gall2_info.sizePolicy().hasHeightForWidth())
        self.gall2_info.setSizePolicy(sizePolicy)
        self.gall2_info.setMaximumSize(QtCore.QSize(16777215, 80))
        self.gall2_info.setObjectName("gall2_info")
        self.gridLayout_9.addWidget(self.gall2_info, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.gall2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.gall2_input = QtWidgets.QLineEdit(self.gall2)
        self.gall2_input.setObjectName("gall2_input")
        self.horizontalLayout_7.addWidget(self.gall2_input)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        Wizard.addPage(self.gall2)
        self.process = QtWidgets.QWizardPage()
        self.process.setObjectName("process")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.process)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.process)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.processing_page = QtWidgets.QLabel(self.process)
        self.processing_page.setObjectName("processing_page")
        self.verticalLayout_4.addWidget(self.processing_page)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.progressBar = QtWidgets.QProgressBar(self.process)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        Wizard.addPage(self.process)
        self.concl = QtWidgets.QWizardPage()
        self.concl.setObjectName("concl")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.concl)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.concl_info = QtWidgets.QLabel(self.concl)
        self.concl_info.setObjectName("concl_info")
        self.gridLayout_7.addWidget(self.concl_info, 0, 0, 1, 1)
        Wizard.addPage(self.concl)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "자동 추가"))
        self.label_4.setText(_translate("Wizard", "자동 추가를 하려는 사이트 종류를 입력해주세요.\n"
"\n"
"개별 페이지에서 짤을 다운 받으시려면 수동 추가 메뉴를 이용해주세요.\n"
"\n"
""))
        self.radioButton_gall.setText(_translate("Wizard", "디시인사이드 갤러리"))
        self.radioButton_tistory.setText(_translate("Wizard", "티스토리 블로그"))
        self.label_10.setText(_translate("Wizard", "검색할 티스토리 주소를 입력해주세요\n"
""))
        self.label.setText(_translate("Wizard", "검색할 갤러리 주소 코드를 입력해주세요\n"
"\n"
"(예: 러블리즈 갤러리 -> lovelyz)\n"
""))
        self.gall1_search.setText(_translate("Wizard", "코드 찾기"))
        self.groupBox.setTitle(_translate("Wizard", "검색 옵션"))
        self.gall1_rec.setText(_translate("Wizard", "개념글만 검색"))
        self.gall1_filter.setText(_translate("Wizard", "제목 필터 적용"))
        self.groupBox_2.setTitle(_translate("Wizard", "분석 결과"))
        self.tistory2_info.setText(_translate("Wizard", "선택한 티스토리:\n"
"\n"
"선택 가능한 페이지 범주:"))
        self.label_12.setText(_translate("Wizard", "다운 받고자 하는 페이지 범주를 입력해 주세요 (예: 1-4,5): "))
        self.groupBox_3.setTitle(_translate("Wizard", "분석 결과"))
        self.gall2_info.setText(_translate("Wizard", "선택한 갤러리:\n"
"\n"
"선택 가능한 페이지 범주:"))
        self.label_14.setText(_translate("Wizard", "다운 받고자 하는 페이지 범주를 입력해 주세요 (예: 1-4,5): "))
        self.label_6.setText(_translate("Wizard", "분석 중입니다. 잠시만 기다려주세요."))
        self.processing_page.setText(_translate("Wizard", "검색 중인 사이트:"))
        self.concl_info.setText(_translate("Wizard", "분석을 종료합니다."))

