# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_duplicate.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.setWindowModality(QtCore.Qt.NonModal)
        Wizard.resize(465, 407)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Wizard.sizePolicy().hasHeightForWidth())
        Wizard.setSizePolicy(sizePolicy)
        Wizard.setWizardStyle(QtWidgets.QWizard.AeroStyle)
        Wizard.setTitleFormat(QtCore.Qt.PlainText)
        Wizard.setSubTitleFormat(QtCore.Qt.PlainText)
        self.intro = QtWidgets.QWizardPage()
        self.intro.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.intro.setTitle("")
        self.intro.setSubTitle("")
        self.intro.setObjectName("intro")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.intro)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.intro)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.intro)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.intro)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.checkBox = QtWidgets.QCheckBox(self.intro)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        Wizard.addPage(self.intro)
        self.process = QtWidgets.QWizardPage()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process.sizePolicy().hasHeightForWidth())
        self.process.setSizePolicy(sizePolicy)
        self.process.setObjectName("process")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.process)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.process)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.processing_page = QtWidgets.QLabel(self.process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.processing_page.sizePolicy().hasHeightForWidth())
        self.processing_page.setSizePolicy(sizePolicy)
        self.processing_page.setScaledContents(False)
        self.processing_page.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.processing_page.setWordWrap(False)
        self.processing_page.setObjectName("processing_page")
        self.verticalLayout_4.addWidget(self.processing_page)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.process)
        self.progressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setBaseSize(QtCore.QSize(0, 30))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 1, 0, 1, 1)
        Wizard.addPage(self.process)
        self.concl = QtWidgets.QWizardPage()
        self.concl.setObjectName("concl")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.concl)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.concl_info = QtWidgets.QLabel(self.concl)
        self.concl_info.setObjectName("concl_info")
        self.gridLayout_7.addWidget(self.concl_info, 0, 0, 1, 1)
        Wizard.addPage(self.concl)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "중복이면말좀해주지"))
        self.label_2.setText(_translate("Wizard", "검사할 폴더를 선택해주세요.\n"
"\n"
"해당 폴더 내에 있는 중복된 파일을 찾아줍니다."))
        self.pushButton.setText(_translate("Wizard", "폴더 찾기"))
        self.checkBox.setText(_translate("Wizard", "중복된 파일 \"중복된 짤\" 폴더로 이동"))
        self.label_6.setText(_translate("Wizard", "분석 중입니다. 잠시만 기다려주세요."))
        self.processing_page.setText(_translate("Wizard", "분석 중인 파일:"))
        self.concl_info.setText(_translate("Wizard", "분석을 종료합니다."))

