# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_info.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(835, 482)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(dialog)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(dialog)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(dialog)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(dialog)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.label_3.setFont(font)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(dialog)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.label_4.setFont(font)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(dialog)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.label_8 = QtWidgets.QLabel(dialog)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "짤 다운로더 정보"))
        self.label_5.setText(_translate("dialog", "<html><head/><body><p><img width=100 src=\"gui/icons/main.png\"/></p></body></html>"))
        self.label.setText(_translate("dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">짤 다운로더</span></p></body></html>"))
        self.label_2.setText(_translate("dialog", "버전 6.0"))
        self.label_7.setText(_translate("dialog", "<html><head/><body><p>짤 다운로더는 디시인사이드 갤러리 및 트위터 등에서 이미지를 다운로드 받는 프로그램입니다.</p></body></html>"))
        self.label_3.setText(_translate("dialog", "<html><head/><body><p>아이콘 출처: <a href=\"https://icons8.com\"><span style=\" text-decoration: underline; color:#0000ff;\">icons8</span></a></p></body></html>"))
        self.label_4.setText(_translate("dialog", "<html><head/><body><p>소스코드와 배포: <a href=\"https://github.com/tucuprum/jjal_downloader\"><span style=\" text-decoration: underline; color:#0000ff;\">GitHub</span></a></p></body></html>"))
        self.label_6.setText(_translate("dialog", "이 프로그램은 GNU GPL v3에 의거하여 배포되고 있습니다."))
        self.label_8.setText(_translate("dialog", "<html><head/><body><p>Copyright (C) 2018 초코맛제티 (<a href=\"http://gallog.dcinside.com/tucuprum\"><span style=\" text-decoration: underline; color:#0000ff;\">http://gallog.dcinside.com/tucuprum</span></a>)</p></body></html>"))

