# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1113, 736)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.loadButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui/icons/icons8-open-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadButton.setIcon(icon1)
        self.loadButton.setIconSize(QtCore.QSize(30, 30))
        self.loadButton.setFlat(True)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 0, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui/icons/icons8-save-as-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon2)
        self.saveButton.setIconSize(QtCore.QSize(30, 30))
        self.saveButton.setFlat(True)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 1, 1)
        self.manualAddButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualAddButton.sizePolicy().hasHeightForWidth())
        self.manualAddButton.setSizePolicy(sizePolicy)
        self.manualAddButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui/icons/icons8-plus-math-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manualAddButton.setIcon(icon3)
        self.manualAddButton.setIconSize(QtCore.QSize(30, 30))
        self.manualAddButton.setFlat(True)
        self.manualAddButton.setObjectName("manualAddButton")
        self.gridLayout.addWidget(self.manualAddButton, 0, 3, 1, 1)
        self.autoAddButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoAddButton.sizePolicy().hasHeightForWidth())
        self.autoAddButton.setSizePolicy(sizePolicy)
        self.autoAddButton.setAutoFillBackground(False)
        self.autoAddButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui/icons/icons8-add-list-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.autoAddButton.setIcon(icon4)
        self.autoAddButton.setIconSize(QtCore.QSize(30, 30))
        self.autoAddButton.setFlat(True)
        self.autoAddButton.setObjectName("autoAddButton")
        self.gridLayout.addWidget(self.autoAddButton, 0, 4, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gui/icons/icons8-minus-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon5)
        self.deleteButton.setIconSize(QtCore.QSize(30, 30))
        self.deleteButton.setFlat(True)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 0, 5, 1, 1)
        self.cleanButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleanButton.sizePolicy().hasHeightForWidth())
        self.cleanButton.setSizePolicy(sizePolicy)
        self.cleanButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("gui/icons/icons8-broom-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cleanButton.setIcon(icon6)
        self.cleanButton.setIconSize(QtCore.QSize(30, 30))
        self.cleanButton.setFlat(True)
        self.cleanButton.setObjectName("cleanButton")
        self.gridLayout.addWidget(self.cleanButton, 0, 6, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 7, 1, 1)
        self.settingButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingButton.sizePolicy().hasHeightForWidth())
        self.settingButton.setSizePolicy(sizePolicy)
        self.settingButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("gui/icons/icons8-tune-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingButton.setIcon(icon7)
        self.settingButton.setIconSize(QtCore.QSize(30, 30))
        self.settingButton.setFlat(True)
        self.settingButton.setObjectName("settingButton")
        self.gridLayout.addWidget(self.settingButton, 0, 8, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 9, 1, 1)
        self.executeButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.executeButton.sizePolicy().hasHeightForWidth())
        self.executeButton.setSizePolicy(sizePolicy)
        self.executeButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("gui/icons/icons8-play-filled-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap("gui/icons/icons8-stop-filled-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.executeButton.setIcon(icon8)
        self.executeButton.setIconSize(QtCore.QSize(30, 30))
        self.executeButton.setCheckable(True)
        self.executeButton.setDefault(False)
        self.executeButton.setFlat(True)
        self.executeButton.setObjectName("executeButton")
        self.gridLayout.addWidget(self.executeButton, 0, 10, 1, 1)
        self.folderButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderButton.sizePolicy().hasHeightForWidth())
        self.folderButton.setSizePolicy(sizePolicy)
        self.folderButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("gui/icons/icons8-view-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folderButton.setIcon(icon9)
        self.folderButton.setIconSize(QtCore.QSize(30, 30))
        self.folderButton.setFlat(True)
        self.folderButton.setObjectName("folderButton")
        self.gridLayout.addWidget(self.folderButton, 0, 11, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 12, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(601, 0))
        self.treeWidget.setAutoFillBackground(True)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setWordWrap(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(120)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.treeWidget.header().setStretchLastSection(True)
        self.graphicsView = QtWidgets.QGraphicsView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.graphicsView.setAlignment(QtCore.Qt.AlignCenter)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionload_list = QtWidgets.QAction(mainWindow)
        self.actionload_list.setObjectName("actionload_list")
        self.actionsave_list = QtWidgets.QAction(mainWindow)
        self.actionsave_list.setObjectName("actionsave_list")
        self.actionclose = QtWidgets.QAction(mainWindow)
        self.actionclose.setObjectName("actionclose")
        self.actionhelp = QtWidgets.QAction(mainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actioninfo = QtWidgets.QAction(mainWindow)
        self.actioninfo.setObjectName("actioninfo")
        self.actionsetting = QtWidgets.QAction(mainWindow)
        self.actionsetting.setObjectName("actionsetting")
        self.actionduplicate = QtWidgets.QAction(mainWindow)
        self.actionduplicate.setObjectName("actionduplicate")
        self.actionclassifier_link = QtWidgets.QAction(mainWindow)
        self.actionclassifier_link.setObjectName("actionclassifier_link")
        self.menu.addAction(self.actionload_list)
        self.menu.addAction(self.actionsave_list)
        self.menu.addSeparator()
        self.menu.addAction(self.actionsetting)
        self.menu.addSeparator()
        self.menu.addAction(self.actionclose)
        self.menu_2.addAction(self.actionhelp)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actioninfo)
        self.menu_3.addAction(self.actionduplicate)
        self.menu_3.addAction(self.actionclassifier_link)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(mainWindow)
        self.actionclose.triggered.connect(mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "짤 다운로더"))
        self.loadButton.setToolTip(_translate("mainWindow", "<html><head/><body><p>작업 불러오기</p></body></html>"))
        self.saveButton.setToolTip(_translate("mainWindow", "<html><head/><body><p>작업 저장하기</p></body></html>"))
        self.manualAddButton.setToolTip(_translate("mainWindow", "<html><head/><body><p>개별 주소 추가하기</p></body></html>"))
        self.manualAddButton.setShortcut(_translate("mainWindow", "Return"))
        self.autoAddButton.setToolTip(_translate("mainWindow", "<html><head/><body><p>자동 주소 추가하기</p></body></html>"))
        self.deleteButton.setToolTip(_translate("mainWindow", "<html><head/><body><p>선택한 내역 지우기</p></body></html>"))
        self.cleanButton.setToolTip(_translate("mainWindow", "<html><head/><body><p>다운로드 완료한 내역 정라하기</p></body></html>"))
        self.settingButton.setToolTip(_translate("mainWindow", "<html><head/><body><p>설정</p></body></html>"))
        self.executeButton.setToolTip(_translate("mainWindow", "<html><head/><body><p>다운로드 시작</p></body></html>"))
        self.folderButton.setToolTip(_translate("mainWindow", "<html><head/><body><p>다운로드 폴더 열기</p></body></html>"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("mainWindow", "주소"))
        self.treeWidget.headerItem().setText(1, _translate("mainWindow", "제목"))
        self.treeWidget.headerItem().setText(2, _translate("mainWindow", "전체 크기"))
        self.treeWidget.headerItem().setText(3, _translate("mainWindow", "진행 상황"))
        self.menu.setTitle(_translate("mainWindow", "파일"))
        self.menu_2.setTitle(_translate("mainWindow", "도움말"))
        self.menu_3.setTitle(_translate("mainWindow", "추가기능"))
        self.actionload_list.setText(_translate("mainWindow", "작업 불러오기"))
        self.actionsave_list.setText(_translate("mainWindow", "작업 저장하기"))
        self.actionclose.setText(_translate("mainWindow", "종료"))
        self.actionhelp.setText(_translate("mainWindow", "도움말"))
        self.actioninfo.setText(_translate("mainWindow", "짤 다운로더 정보"))
        self.actionsetting.setText(_translate("mainWindow", "설정"))
        self.actionduplicate.setText(_translate("mainWindow", "중복 짤 제거"))
        self.actionclassifier_link.setText(_translate("mainWindow", "얼굴 인식 분류 (링크)"))

